install.packages("rstudioapi")
library(rstudioapi)
install.packages("keychain")
install.packages("crypto")
library(crypto)

library(rlang)
library(usethis)
library(devtools)
devtools::install_github("jessevent/crypto")
